[package]
name = "pipely"
version = "0.1.0"
edition = "2024"
description = "A pipeline-style procedural macro for chaining Rust expressions"
license = "MIT OR Apache-2.0"
repository = "https://github.com/JonasAlmaas/rust-pipe"
readme = "README.md"
keywords = ["pipeline", "pipe", "macro", "chaining"]
categories = ["rust-patterns", "development-tools"]
exclude = [".github/"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.4", features = ["full", "visit-mut"] }
